[package]
name = "jit"
version = "0.1.0"
edition = "2021"

[dependencies]
arbutil = { path = "../arbutil/" }
ark-bls12-381 = "0.4.0"
ark-serialize = { version = "0.4", features = ["derive"] }
wasmer = "3.1.0"
wasmer-compiler-cranelift = "3.1.0"
wasmer-compiler-llvm = { version = "3.1.0", optional = true }
eyre = "0.6.5"
parking_lot = "0.12.1"
rand = { version = "0.8.4", default-features = false }
rand_pcg = { version = "0.3.1", default-features = false }
thiserror = "1.0.33"
hex = "0.4.3"
structopt = "0.3.26"
sha3 = "0.9.1"
libc = "0.2.132"
ouroboros = "0.16.0"
sequencer = { git = "https://github.com/EspressoSystems/espresso-sequencer" }
serde_json = "1.0"
tagged-base64 = { git = "https://github.com/EspressoSystems/tagged-base64", tag = "0.3.4" }
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
sha2 = { version = "0.10.1" }
jf-primitives = { git = "https://github.com/EspressoSystems/jellyfish", features = [
    "test-srs",
] }

[features]
llvm = ["dep:wasmer-compiler-llvm"]
