version: "3.9"
services:
  espresso-dev-node:
    image: ghcr.io/espressosystems/espresso-sequencer/espresso-dev-node:release-fix-cors
    ports:
      - "$ESPRESSO_SEQUENCER_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
      - "$ESPRESSO_BUILDER_PORT:$ESPRESSO_BUILDER_PORT"
      - "$ESPRESSO_DEV_NODE_PORT:$ESPRESSO_DEV_NODE_PORT"
    environment:
      - ESPRESSO_BUILDER_PORT
      - ESPRESSO_DEPLOYER_ACCOUNT_INDEX
      - ESPRESSO_DEV_NODE_PORT
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_DATABASE_MAX_CONNECTIONS=25
      - ESPRESSO_DEV_NODE_EPOCH_HEIGHT
      - ESPRESSO_SEQUENCER_STORAGE_PATH=/data/espresso
      # Currently we don't need the dev node to deploy Espresso contracts.
      # We can skip them and save some time.
      # These contract addresses are incorrect, but it doesn't matter.
      - ESPRESSO_DEV_NODE_L1_DEPLOYMENT=skip
      - ESPRESSO_SEQUENCER_LIGHT_CLIENT_PROXY_ADDRESS=0x0f1f89aaf1c6fdb7ff9d361e4388f5f3997f12a8
      - ESPRESSO_SEQUENCER_STAKE_TABLE_ADDRESS=0x63e6dde6763c3466c7b45be880f7ee5dc2ca3e25
      - ESPRESSO_SEQUENCER_STAKE_TABLE_PROXY_ADDRESS=0x9f5eac3d8e082f47631f1551f1343f23cd427162
      - RUST_LOG=WARN
      - RUST_LOG_FORMAT
      - ESPRESSO_DEV_NODE_VERSION=0.4
    volumes:
      - espresso_storage:/data/espresso
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  espresso_storage:
