name: Espresso Docker Image

inputs:
  images:
    required: true
    type: string
  target:
    required: true
    type: string
  platforms:
    required: true
    type: string

runs:
  using: composite
  steps:

    - name: Generate docker metadata
      uses: docker/metadata-action@v4
      id: metadata
      with:
        images: ${{ inputs.images }}

    - name: Build and push docker
      uses: docker/build-push-action@v4
      with:
        target: ${{ inputs.target }}
        push: ${{ github.event_name != 'pull_request'  }}
        tags: ${{ steps.metadata.outputs.tags  }}
        labels: ${{ steps.metadata.outputs.labels  }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
