#!/usr/bin/env bash
set -euo pipefail

arch=$(uname -m)
os=$(uname -s)

if [ "$arch" = "arm64" ] || [ "$arch" = "aarch64" ]; then
    if [ "$os" = "Darwin" ]; then
        triple="aarch64-apple-darwin.dylib"
    else
        triple="aarch64-unknown-linux-gnu.so"
    fi
elif [ "$arch" = "x86_64" ]; then
    if [ "$os" = "Darwin" ]; then
        triple="x86_64-apple-darwin.dylib"
    else
        triple="x86_64-unknown-linux-gnu.so"
    fi
else
    echo "ERROR: $arch is not supported"
    exit 1
fi

go get github.com/EspressoSystems/espresso-network/sdks/go
# This script assumes that you have the `espresso-network-lib-utility` command
# installed, and available in your PATH.
command -v espresso-network-lib-utility >/dev/null 2>&1 || {
    cat <<'EOF' >&2
ERROR: The command 'espresso-network-lib-utility' is not found in your PATH.
Please ensure you have the Espresso Go SDK installed, which includes this command.

You can install it by running:
    go install github.com/EspressoSystems/espresso-network/sdks/go/cmd/espresso-network-lib-utility

If go install results in an error, you may need to ensure that the library
exists in your cache before running the command again.  The command was first
made available in release `v0.2.8`.  So you should be able to ensure it works by running:
    go run github.com/EspressoSystems/espresso-network/sdks/go/cmd/espresso-network-lib-utility@v0.2.8
    go install github.com/EspressoSystems/espresso-network/sdks/go/cmd/espresso-network-lib-utility@v0.2.8

This command will be installed to your go bin directory (defaults to ~/go/bin),
however, this command simply needs to be in your PATH for the script to work.
If you feel uncomfortable adding the go bin directory to your PATH, you can
create a symlink to the command in a directory that is already in your PATH.
EOF
    exit 1
}

fileName="libespresso_crypto_helper-$triple"

# Dynamically fetch the latest Go SDK release tag from GitHub
latest_tag=$(curl -s https://api.github.com/repos/EspressoSystems/espresso-network/releases | grep -o 'sdks/go/v[0-9.]*' | head -n 1)
if [ -z "$latest_tag" ]; then
    echo "ERROR: Could not fetch latest Espresso Go SDK release tag."
    latest_tag=sdks/go/v0.2.2
fi
version=${latest_tag#sdks/go/}
echo "using Espresso Go SDK release tag: $latest_tag, version: $version"
checksum=$(curl -L "https://github.com/EspressoSystems/espresso-network/releases/download/${latest_tag//\//%2F}/$fileName.sha256")

echo "Checksum: $checksum"

url="https://github.com/EspressoSystems/espresso-network/releases/download/${latest_tag//\//%2F}/$fileName"

echo "downloading from $url"

mkdir -p ./target/lib
curl -L "$url" -o ./target/lib/$fileName

espresso-network-lib-utility clean -v $version
espresso-network-lib-utility link -c $checksum -f ./target/lib/$fileName -v $version
