#!/usr/bin/env bash
# This script runs the Espresso tests in ./system_tests only.
set -euo pipefail

go test \
  -v \
  -timeout 45m \
  -p 1 \
  ./system_tests/... \
  -run 'TestEspressoRegressionTransactionStreamerToEspressoThroughput'
