[package]
name = "espresso-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
caller-env = { path = "../../caller-env/", default-features = false, features = ["static_caller"] }
espresso-crypto-helper = {path = "../../espresso-crypto-helper"}

[lib]
crate-type = ["cdylib", "rlib"]
