name: Espresso E2E test CI

on:
  workflow_dispatch:
  merge_group:
  pull_request:
  push:
    branches:
      - integration

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Espresso E2E
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies
        run: >
          sudo apt update && sudo apt install -y wabt gotestsum
          cmake build-essential bison golang clang make wabt

      - name: free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: true

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Install wasm-ld
        run: |
          sudo apt-get update && sudo apt-get install -y lld-14
          sudo ln -s /usr/bin/wasm-ld-14 /usr/local/bin/wasm-ld

      - name: Install rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: 'wasm32-unknown-unknown, wasm32-wasi'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install rust nightly
        uses: actions-rs/toolchain@v1
        id: install-rust-nightly
        with:
          profile: minimal
          toolchain: "nightly"

      - name: Install rust wasm targets
        run: rustup target add wasm32-wasi wasm32-unknown-unknown

      - name: Install nightly wasm targets
        run: |
          rustup component add rust-src --toolchain nightly
          rustup target add wasm32-unknown-unknown --toolchain nightly

      - name: Cache Build Products
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ matrix.test-mode }}
          restore-keys: ${{ runner.os }}-go-

      - name: Cache Rust Build Products
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git/
            arbitrator/target/
            arbitrator/wasm-libraries/target/
            arbitrator/wasm-libraries/soft-float/SoftFloat/build
            target/etc/initial-machine-cache/
          key: ${{ runner.os }}-cargo-${{ steps.install-rust.outputs.rustc_hash }}-min-${{ hashFiles('arbitrator/Cargo.lock') }}-${{ matrix.test-mode }}
          restore-keys: ${{ runner.os }}-cargo-${{ steps.install-rust.outputs.rustc_hash }}-

      - name: Cache cbrotli
        uses: actions/cache@v3
        id: cache-cbrotli
        with:
          path: |
            target/include/brotli/
            target/lib-wasm/
            target/lib/libbrotlicommon-static.a
            target/lib/libbrotlienc-static.a
            target/lib/libbrotlidec-static.a
          key: ${{ runner.os }}-brotli-${{ hashFiles('scripts/build-brotli.sh') }}-${{ hashFiles('.github/workflows/arbitrator-ci.yaml') }}-${{ matrix.test-mode }}
          restore-keys: ${{ runner.os }}-brotli-

      - name: Build cbrotli-local
        if: steps.cache-cbrotli.outputs.cache-hit != 'true'
        run: ./scripts/build-brotli.sh -l

      - name: Build cbrotli-wasm in docker
        if: steps.cache-cbrotli.outputs.cache-hit != 'true'
        run: ./scripts/build-brotli.sh -w -d


      - name: Build
        run: make build build-replay-env -j

      - name: Install docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1.2.1
        with:
          version: '2.22.0'

      - name: Pull latest espresso-dev-node image
        run: |
          cd system_tests/espresso-e2e
          docker compose pull

      - name: Run espresso migration test
        run: |
          gotestsum --format=testname short-verbose --packages=./system_tests --rerun-fails=1 -- -v -timeout 15m -run 'TestEspressoMigration'

      - name: Run E2E test
        run: |
          gotestsum --format=testname short-verbose --packages=./system_tests --rerun-fails=1 -- -v -timeout 35m -run 'TestEspressoE2E'

      - name: Run sovereign sequencer test
        run: |
          gotestsum --format=testname short-verbose --packages=./system_tests --rerun-fails=1 -- -v -timeout 15m -run 'TestSovereignSequencer'
