# This is a simpler version of the upstream `docker.yml`.
#
# The differences are:
# - Uses GHA docker cache.
# - Does not export the wavm module root as artifact.
name: Espresso Docker build CI
run-name: Docker build CI triggered from @${{ github.actor }} of ${{ github.head_ref }}

on:
  workflow_dispatch:
  merge_group:
  pull_request:
  push:
    branches:
      - master
      - develop
      - integration

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NITRO_IMAGE: "ghcr.io/espressosystems/nitro-espresso-integration/nitro-node"

jobs:
  docker_build:
    strategy:
      matrix:
        platform: [ "linux/amd64", "linux/arm64" ]
        include:
          - platform: "linux/amd64"
            runs-on: "ubuntu-latest"
          - platform: "linux/arm64"
            runs-on: "ARM64"

    runs-on: [ "${{ matrix.runs-on }}" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Repo
        uses: docker/login-action@v3
        # if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - uses: ./.github/actions/docker-image
        with:
          images: ${{ env.NITRO_IMAGE }}
          target: nitro-node
          platforms: ${{ matrix.platform }}

      # - uses: ./.github/actions/docker-image
      #   with:
      #     images: ghcr.io/espressosystems/nitro-espresso-integration/nitro-node-dev
      #     target: nitro-node-dev
      #     platforms: ${{ matrix.platform }}

  merge_docker_images:
      runs-on: ubuntu-latest
      needs:
        - docker_build
      steps:
        - name: Download digests
          uses: actions/download-artifact@v3
          with:
            name: digests
            path: /tmp/digests

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ${{ env.NITRO_IMAGE }}

        - name: Login to Github Container Repo
          uses: docker/login-action@v2
          # if: github.event_name != 'pull_request'
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner  }}
            password: ${{ secrets.GITHUB_TOKEN  }}

        - name: Create manifest list and push
          working-directory: /tmp/digests
          run: |
            docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
              $(printf '${{ env.NITRO_IMAGE }}@sha256:%s ' *)
        - name: Inspect image
          run: |
            docker buildx imagetools inspect ${{ env.NITRO_IMAGE }}:${{ steps.meta.outputs.version }}
