name: Espresso Regression test CI

on:
  workflow_run:
    workflows: ["Espresso Docker build CI"]
    types: [completed]

  workflow_dispatch:
    inputs:
      image:
        type: choice
        default: dev
        required: true
        description: "Image to use for the regression test"
        options:
          - dev # build from source
          - custom # use custom image
      custom_image: # please make sure this image is compatible with the nitro-testnode submodule
        type: string
        required: false
        description: "Custom image to use for the regression test"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  debug:
    name: Output variables
    runs-on: ubuntu-latest
    steps:
      - name: Output variables
        run: |
          echo "github.event_name=${{ github.event_name }}"
          echo "github.event.workflow_run.ref=${{ github.event.workflow_run.ref }}"
          echo "github.event.workflow_run.head_branch=${{ github.event.workflow_run.head_branch }}"

  test:
    name: Espresso Regression test
    runs-on: ubuntu-24.04-8core
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && startsWith(github.event.workflow_run.head_branch, 'v'))
    steps:
      - name: Setup environment variables
        run: |
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            TAG_NAME=${{ github.event.workflow_run.head_branch }}
            echo "ESPRESSO_VERSION=ghcr.io/espressosystems/nitro-espresso-integration/nitro-node:$TAG_NAME" >> $GITHUB_ENV
          elif [ "${{ github.event.workflow_dispatch.inputs.image }}" = "custom" ]; then
            echo "ESPRESSO_VERSION=${{ github.event.workflow_dispatch.inputs.custom_image }}" >> $GITHUB_ENV
          else
            echo "ESPRESSO_DEV=true" >> $GITHUB_ENV
          fi

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.0.0
          cache: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Transaction Streamer regression test
        run: |
          bash scripts/run-transaction-streamer-regression-ci-tests

      - name: Run regression test
        run: |
          echo "ESPRESSO_VERSION=${{ env.ESPRESSO_VERSION }}"
          echo "ESPRESSO_DEV=${{ env.ESPRESSO_DEV }}"
          if [ -z "$ESPRESSO_VERSION" ] && [ -z "$ESPRESSO_DEV" ]; then
            echo "Neither ESPRESSO_VERSION nor ESPRESSO_DEV is set. Exiting."
            exit 1
          fi
          cd nitro-testnode
          ./regression-test.bash
